## docker-compose.yml
#
#services:
#  # -------------------- Go 后端应用服务 --------------------
#  backend:
#    build: smart_fox2
#    container_name: smart-fox-backend
#    ports:
#      - "3002:3002"
#    volumes:
#      - ./log:/app/log
#    environment:
#      # 数据库连接配置
#      MYSQL_HOST: mysql-db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1056915610q
#      MYSQL_DB: rg
#      GIN_MODE: release
#      # 定义的 judge 服务的名称
#      # Docker 自动将 "judge" 解析为 judge 容器的 IP 地址
#      JUDGE_URL: http://judge:8080
#    restart: always
#    depends_on:
#      - mysql-db
#      - judge # 确保 judge 服务在 backend 之前启动
#
#  # -------------------- MySQL 数据库服务 --------------------
#  mysql-db:
#    image: mysql:8.0
#    container_name: smart-fox-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 1056915610q
#      MYSQL_DATABASE: rg
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
#
#  # -------------------- Judge 评测服务 --------------------
#  judge:
#    build:
#      context: smart_fox2/Judger # 构建上下文是 Judger 目录
#    container_name: smart-fox-judge
#    restart: always
#    ports:
#      - "8080:8080"
#
#volumes:
#  mysql-data:
# your-project/docker-compose.yml

services:
  # -------------------- React 前端服务 --------------------
  frontend:
    build:
      context: ./front
    container_name: smart-fox-frontend
    ports:
      # 电脑的 3000 端口映射到容器的 80 端口 (Nginx)
      - "3000:80"
    restart: always
    depends_on:
      - backend

  # -------------------- Go 后端服务 --------------------
  backend:
    build:
      context: ./smart_fox2
    container_name: smart-fox-backend
    ports:
      - "3002:3002"
    volumes:
      - ./smart_fox2/log:/app/log
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1056915610q
      MYSQL_DB: rg
      GIN_MODE: release
      JUDGE_URL: http://judge:8080
    restart: always
    depends_on:
      - mysql-db
      - judge

  # -------------------- MySQL 数据库服务 --------------------
  mysql-db:
    image: mysql:8.0
    container_name: smart-fox-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1056915610q
      MYSQL_DATABASE: rg
    ports:
      - "3307:3006"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./smart_fox2/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # -------------------- Python 评测服务 --------------------
  judge:
    build:
      context: ./smart_fox2/Judger
    container_name: smart-fox-judge
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql-data: