apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: todo-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: MYSQL_HOST
          value: "mysql-db" # 使用数据库 Service 的名称
        - name: JUDGE_URL
          value: "http://judge:8080" # 使用评测服务 Service 的名称
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_DB
          value: "rg"
        - name: GIN_MODE
          value: "release"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  selector:
    app: todo-backend
  ports:
  - port: 3002
    targetPort: 3002
  type: LoadBalancer # 自动将服务暴露在 localhost:3002