apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa # ServiceAccount 名

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io