apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-deployment
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
      - name: judge
        image: anuanshu/smart-judge:latest # 使用本地构建的镜像
        imagePullPolicy: Always # 优先使用本地镜像
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: judge # 后端服务用来连接评测服务的内部 DNS 名称
spec:
  selector:
    app: judge
  ports:
  - port: 8080
  type: ClusterIP